routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', "UI\UIHomeController@index");

Route::get('/home', 'HomeController@index')->name('home');



// My Routes
Route::group(['middleware' => ['admin']], function() {
    Route::resource('admin/categories', "Admin\AdminCategoriesController", array('as' => 'admin'));

    Route::resource('admin/providers', "Admin\AdminProvidersController", array('as' => 'admin'));

    Route::resource('admin/promotions', "Admin\AdminPromotionsController", array('as' => 'admin'));

    Route::resource('admin/products', "Admin\AdminProductsController", array('as' => 'admin'));

    Route::resource('admin/roles', "Admin\AdminRolesController", array('as' => 'admin'));

    Route::resource('admin/users', "Admin\AdminUsersController", array('as' => 'admin'));

//------ Admin Orders ------
    Route::resource('admin/orders', "Admin\AdminOrdersController", array('as' => 'admin'));
    Route::post("admin/orders/updateindex", "Admin\AdminOrdersController@updateAjax")->name('admin.orders.updateindex');

    Route::resource('admin/comments', "Admin\AdminCommentsController", array('as' => 'admin'));
    Route::post("admin/comments/update", "Admin\AdminCommentsController@updateAjax")->name('admin.comments.update');

    Route::resource('admin/media', "Admin\AdminMediaController", array('as' => 'admin'));

    Route::get('admin/products/{id}/provider', ['uses' => 'Admin\AdminProductsController@getProviderById']);
    Route::get('admin/media/{id}/product', ['uses' => 'Admin\AdminMediaController@getProductById']);
});


Route::resource("/home", "UI\UIHomeController");

Route::get("/product/{id}", "UI\UIProductDetailController@index")->name('product.index');
Route::post("/product/{id}/comment", "UI\UIProductDetailController@addComment")->name('product.addcomment');
Route::get('/product/{id}/delete', 'UI\UIProductDetailController@deleteComment')->name('product.deletecomment');

Route::get("/home/category/{id}", "UI\UIHomeController@getProByCate")->name('home.getProByCate');
Route::get("/home/searchbyprice/{data}", "UI\UIHomeController@getProByPrice")->name('home.getProByPrice');

//--- UI ----
Route::post("user/login", "UI\UIUserController@login")->name('user.login');
//Route::post("user/logout", "UI\UIUserController@login")->name('user.logout');

Route::get('user/register', 'UI\UIUserController@registerShow')->name('user.register');
Route::post('user/register', 'UI\UIUserController@Register')->name('user.register.submit');
Route::get('user/verifyemail/{confirm_code}', 'UI\UIUserController@verifyEmail')->name('user.verifyemail');

// ----------- ACCOUNT ----------------
Route::group(['middleware' => ['logged']], function() {
    Route::get('user/account/{id}', 'UI\UIAccountController@show')->name('user.account');
    Route::get('user/order/{id}', 'UI\UIAccountController@orderDetail')->name('user.orderdetail');
    Route::get('user/profile/{id}', 'UI\UIAccountController@profile')->name('user.profile');
    Route::post('user/profile/{id}', 'UI\UIAccountController@profileUpdate')->name('user.profile.update');
    Route::post('user/order/canceled', 'UI\UIAccountController@orderCanceled')->name('user.ordercanceled');
    Route::put('user/profile/changepass', 'UI\UIAccountController@changePass')->name('user.changepass');
    Route::get('user/profile/requestmail/{id}', 'UI\UIAccountController@sendMail')->name('user.sendmail');
});

//------ Cart ------
Route::post("cart/addcart", "UI\UICartController@addCart")->name('cart.addcart');
Route::post("cart/plus", "UI\UICartController@plusCart")->name('cart.plus');
Route::post("cart/minus", "UI\UICartController@minusCart")->name('cart.minus');
Route::post("cart/remove", "UI\UICartController@removeItem")->name('cart.remove');
Route::get("cart", "UI\UICartController@show")->name("cart");
Route::get("checkout", "UI\UICartController@checkout")->name("checkout");
Route::post("checkout", "UI\UICartController@checkoutSubmit")->name("checkout");
Route::get("shipping", "UI\UICartController@shipping")->name("shipping");
Route::post("shippingAgree", "UI\UICartController@shippingSubmit")->name("shippingAgree");



//Route::get("/search","UI\UIHomeController@search")->name('home.search');
Route::get("/search", "UI\UIHomeController@search")->name('home.search');
Route::get("/home/searchbyprice/{data}", "UI\UIHomeController@getProByPrice")->name('home.getProByPrice');


//Make auth for routes
Auth::routes();

resources/views/layouts/admincomponents/leftmenu.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ Auth::user()->avatar() ? asset(Auth::user()->avatar()->path) : asset('admin/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ Auth::user()->name}}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
<!--        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>-->
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MENU</li>
            <li class="active treeview">
                <a href="index_Op.html">
                    <i class="fa fa-dashboard"></i> <span>Admin Dashboard</span>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-cubes blue"></i>
                    <span>Sản phẩm</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('admin.products.index') }}"><i class="fa fa-circle-o"></i> Tất cả sản phẩm</a></li>
                    <li><a href="{{ route('admin.products.create') }}"><i class="fa fa-circle-o"></i> Thêm sản phẩm</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-tasks green"></i>
                    <span>Danh mục Sản phẩm</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('admin.categories.index') }}"><i class="fa fa-circle-o"></i> Tất cả danh mục</a></li>
                    <li><a href="{{ route('admin.categories.create') }}"><i class="fa fa-circle-o"></i> Thêm danh mục</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-percent red"></i>
                    <span>Khuyến mãi</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('admin.promotions.index') }}"><i class="fa fa-circle-o"></i> Tất cả khuyến mãi</a></li>
                    <li><a href="{{ route('admin.promotions.create') }}"><i class="fa fa-circle-o"></i> Thêm khuyến mãi</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-gg-circle cyan"></i>
                    <span>Nhà cung cấp</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('admin.providers.index') }}"><i class="fa fa-circle-o"></i> Tất cả nhà cung cấp</a></li>
                    <li><a href="{{ route('admin.providers.create') }}"><i class="fa fa-circle-o"></i> Thêm mới</a></li>
                </ul>
            </li>
            <li class="">
                <a href="{{ route('admin.orders.index') }}">
                    <i class="fa fa-shopping-cart yellow"></i> <span>Đơn hàng</span>
                </a>
                <!-- <ul class="treeview-menu">
                        <li><a href="pages/forms/general.html"><i class="fa fa-circle-o"></i> </a></li>
                        <li><a href="pages/forms/advanced.html"><i class="fa fa-circle-o"></i> Advanced Elements</a></li>
                        <li><a href="pages/forms/editors.html"><i class="fa fa-circle-o"></i> Editors</a></li>
                </ul> -->
            </li>
               <li class="">
                <a href="{{ route('admin.comments.index') }}">
                    <i class="fa fa-comments yellow"></i> <span>Bình luận</span>
                </a>
                <!-- <ul class="treeview-menu">
                        <li><a href="pages/forms/general.html"><i class="fa fa-circle-o"></i> </a></li>
                        <li><a href="pages/forms/advanced.html"><i class="fa fa-circle-o"></i> Advanced Elements</a></li>
                        <li><a href="pages/forms/editors.html"><i class="fa fa-circle-o"></i> Editors</a></li>
                </ul> -->
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-user-circle purple"></i> <span>Tài khoản người dùng</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('admin.users.index') }}"><i class="fa fa-circle-o"></i> Tất cả tài khoản</a></li>
                    <li><a href="{{ route('admin.users.create') }}"><i class="fa fa-circle-o"></i> Thêm mới tài khoản</a></li>
                </ul>
            </li>
            <li class="">
                <a href="{{ route('admin.media.index') }}">
                    <i class="fa fa-picture-o maroon"></i> <span>Media</span>
                </a>

            </li>

        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

resources/views/layouts/admincomponents/navbar.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>A</b>LT</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Admin</b>Page</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div style="display: inline-block; font-size: 30px; float: left; color: #EFDE34; padding-left: 20%;">
            <b>Royal Shop</b>
        </div>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ Auth::user()->avatar()? asset(Auth::user()->avatar()->path) : asset('admin/dist/img/user2-160x160.jpg') }}" class="user-image" alt="User Image">
                        <span class="hidden-xs">{{Auth::user()->name}}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="{{ Auth::user()->avatar()? asset(Auth::user()->avatar()->path) : asset('admin/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">

                            <p>
                                {{Auth::user()->name}}
                                <small>Administrator</small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <li class="user-body">
                            <div class="row">
                                <div class="col-xs-4 text-center">
                                    <a href="#">Followers</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Sales</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Friends</a>
                                </div>
                            </div>
                            <!-- /.row -->
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="#" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/admincomponents/rightmenu.blade.php
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-warning pull-right">50%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->
        <!-- Stats tab content -->
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        <!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->

                <h3 class="control-sidebar-heading">Chat Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right">
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside>
<!-- /.control-sidebar -->