routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', "UI\UIHomeController@index");

Route::get('/home', 'HomeController@index')->name('home');



// My Routes
Route::group(['middleware' => ['admin']], function() {
    Route::resource('admin/categories', "Admin\AdminCategoriesController", array('as' => 'admin'));

    Route::resource('admin/providers', "Admin\AdminProvidersController", array('as' => 'admin'));

    Route::resource('admin/promotions', "Admin\AdminPromotionsController", array('as' => 'admin'));

    Route::resource('admin/products', "Admin\AdminProductsController", array('as' => 'admin'));

    Route::resource('admin/roles', "Admin\AdminRolesController", array('as' => 'admin'));

    Route::resource('admin/users', "Admin\AdminUsersController", array('as' => 'admin'));

//------ Admin Orders ------
    Route::resource('admin/orders', "Admin\AdminOrdersController", array('as' => 'admin'));
    Route::post("admin/orders/updateindex", "Admin\AdminOrdersController@updateAjax")->name('admin.orders.updateindex');

    Route::resource('admin/comments', "Admin\AdminCommentsController", array('as' => 'admin'));
    Route::post("admin/comments/update", "Admin\AdminCommentsController@updateAjax")->name('admin.comments.update');

    Route::resource('admin/media', "Admin\AdminMediaController", array('as' => 'admin'));

    Route::get('admin/products/{id}/provider', ['uses' => 'Admin\AdminProductsController@getProviderById']);
    Route::get('admin/media/{id}/product', ['uses' => 'Admin\AdminMediaController@getProductById']);
});


Route::resource("/home", "UI\UIHomeController");

Route::get("/product/{id}", "UI\UIProductDetailController@index")->name('product.index');
Route::post("/product/{id}/comment", "UI\UIProductDetailController@addComment")->name('product.addcomment');
Route::get('/product/{id}/delete', 'UI\UIProductDetailController@deleteComment')->name('product.deletecomment');

Route::get("/home/category/{id}", "UI\UIHomeController@getProByCate")->name('home.getProByCate');
Route::get("/home/searchbyprice/{data}", "UI\UIHomeController@getProByPrice")->name('home.getProByPrice');

//--- UI ----
Route::post("user/login", "UI\UIUserController@login")->name('user.login');
//Route::post("user/logout", "UI\UIUserController@login")->name('user.logout');

Route::get('user/register', 'UI\UIUserController@registerShow')->name('user.register');
Route::post('user/register', 'UI\UIUserController@Register')->name('user.register.submit');
Route::get('user/verifyemail/{confirm_code}', 'UI\UIUserController@verifyEmail')->name('user.verifyemail');

// ----------- ACCOUNT ----------------
Route::group(['middleware' => ['logged']], function() {
    Route::get('user/account/{id}', 'UI\UIAccountController@show')->name('user.account');
    Route::get('user/order/{id}', 'UI\UIAccountController@orderDetail')->name('user.orderdetail');
    Route::get('user/profile/{id}', 'UI\UIAccountController@profile')->name('user.profile');
    Route::post('user/profile/{id}', 'UI\UIAccountController@profileUpdate')->name('user.profile.update');
    Route::post('user/order/canceled', 'UI\UIAccountController@orderCanceled')->name('user.ordercanceled');
    Route::put('user/profile/changepass', 'UI\UIAccountController@changePass')->name('user.changepass');
    Route::get('user/profile/requestmail/{id}', 'UI\UIAccountController@sendMail')->name('user.sendmail');
});

//------ Cart ------
Route::post("cart/addcart", "UI\UICartController@addCart")->name('cart.addcart');
Route::post("cart/plus", "UI\UICartController@plusCart")->name('cart.plus');
Route::post("cart/minus", "UI\UICartController@minusCart")->name('cart.minus');
Route::post("cart/remove", "UI\UICartController@removeItem")->name('cart.remove');
Route::get("cart", "UI\UICartController@show")->name("cart");
Route::get("checkout", "UI\UICartController@checkout")->name("checkout");
Route::post("checkout", "UI\UICartController@checkoutSubmit")->name("checkout");
Route::get("shipping", "UI\UICartController@shipping")->name("shipping");
Route::post("shippingAgree", "UI\UICartController@shippingSubmit")->name("shippingAgree");



//Route::get("/search","UI\UIHomeController@search")->name('home.search');
Route::get("/search", "UI\UIHomeController@search")->name('home.search');
Route::get("/home/searchbyprice/{data}", "UI\UIHomeController@getProByPrice")->name('home.getProByPrice');


//Make auth for routes
Auth::routes();

app/Promotion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Promotion extends Model {

    protected $fillable = [
        'id',
        'value',
        'is_active',
        'description'
    ];

}

resources/views/admin/promotions/create.blade.php
@extends ('layouts.admin')

@section('content')


<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Thêm mới khuyến mãi</h3>
    </div>
    <div class="row">
        <div class="col-md-8">
            <form role="form" action="{{ route('admin.promotions.store') }}" method="post" enctype='multipart/form-data'>
                <div class="box-body">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
                    <div class=" form-group {{ $errors->has('value') ? 'has-error' : '' }}">
                        <label for="value">Giá trị khuyến mãi:</label>
                        <input type="number" id="value" name="value" class="form-control"  value="{{ old('value') }}">
                        <span class="text-danger">{!! $errors->first('value') !!}</span>
                    </div>  

                    <div class=" form-group {{ $errors->has('description') ? 'has-error' : '' }}">
                        <label for="description">Mô tả khuyến mãi:</label>
                        <input type="text" class="form-control" id="description" name="description" value="{{ old('description') }}">
                        <span class="text-danger">{{ $errors->first('description') }}</span>
                    </div> 

                    <div class="form-group">
                        <input type="submit" class="btn btn-success" value="Lưu" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


@endsection

resources/views/admin/promotions/edit.blade.php
@extends ('layouts.admin')

@section('content')
@if (Session::has('notification'))
<div class="alert alert-success" id="notify">
    <button data-dismiss="alert" class="close">×</button>
    {!! Session::get('notification') !!}
</div>
@endif

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Chỉnh sửa khuyến mãi</h3>
    </div>
    <div class="row">
        <div class="col-md-8">
            <form role="form" action="{{ route('admin.promotions.update',$promotion->id) }}" method="POST" enctype='multipart/form-data'>
                <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
                <input type="hidden" name="_method" value="PUT">
                <div class="box-body">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
                    
                    <div class=" form-group {{ $errors->has('value') ? 'has-error' : '' }}" >
                        <label for="value">Giá trị khuyến mãi:</label>
                        <input type="number" id="value" name="value" class="form-control"  value="{{ $promotion->value  }}">
                        <span class="text-danger">{!! $errors->first('value') !!}</span>
                    </div>  

                    <div class=" form-group {{ $errors->has('description') ? 'has-error' : '' }}">
                        <label for="description">Mô tả khuyến mãi:</label>
                        <input type="text" class="form-control" id="description" name="description" value="{{ $promotion->description  }}">
                        <span class="text-danger">{{ $errors->first('description') }}</span>
                    </div> 

                    <div class="  form-group {{ $errors->has('is_active') ? 'has-error' : '' }}">
                        <label for="is_active">Hoạt động:</label>
                        <input type="checkbox" id="is_active" name="is_active" value="1" {{ $promotion->is_active == 1 ? 'checked' : '' }} >

                        <span class="text-danger">{{ $errors->first('is_active') }}</span>
                    </div> 

                    <div class="form-group">
                        <input type="submit" class="btn btn-success" value="Chỉnh sửa" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@stop

resources/views/admin/promotions/index.blade.php
@extends ('layouts.admin')

@section('content')
@if (Session::has('notification'))
<div class="alert alert-success" id="notify">
    <button data-dismiss="alert" class="close">×</button>
    {!! Session::get('notification') !!}
</div>
@endif
<div class="row">
    <div class="col-sm-12">
        <div class="box">
            <div class="box-header">
                <h1>Khuyến mãi</h1>

                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>Giá trị khuyến mãi</th>
                                <th>Mô tả</th>
                                <th>Hoạt động</th>
                        </thead>
                        <tbody>
                            @if($promotions)
                            @foreach($promotions as $promotion)
                            <tr>
                                <td>{{$promotion->id}}</td>
                                <td id="name_{{$promotion->id}}">{{$promotion->value.' %'}}</td>
                                <td>{{$promotion->description}}</td>
                                <td>{{$promotion->is_active?'1':'0'}}</td>
                                <td>
                                    <div style="display: block; width: max-content">
                                        <a class="button-a edit-button " href="{{ route('admin.promotions.edit', $promotion->id) }}" 
                                           title="Chỉnh sửa"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>&nbsp;

                                        <a class="button-a delete-button delete-fnt" data-type="2" data-id="{{$promotion->id }}"
                                           title="Xóa"><i class="fa fa-trash-o" aria-hidden="true"></i></a>&nbsp;

                                        <form id="fnt_{{$promotion->id}}" action="{{ route('admin.promotions.destroy', $promotion->id) }}" method="POST" >
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
                                        </form>
                                    </div>
                                </td>
                            </tr>

                            @endforeach

                            @endif

                        </tbody>
                    </table>
                    <div style="text-align: center">
                        {{ $promotions->render() }}
                    </div>
                </div>
            </div>
        </div>
    </div>



    @endsection