routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', "UI\UIHomeController@index");

Route::get('/home', 'HomeController@index')->name('home');



// My Routes
Route::group(['middleware' => ['admin']], function() {
    Route::resource('admin/categories', "Admin\AdminCategoriesController", array('as' => 'admin'));

    Route::resource('admin/providers', "Admin\AdminProvidersController", array('as' => 'admin'));

    Route::resource('admin/promotions', "Admin\AdminPromotionsController", array('as' => 'admin'));

    Route::resource('admin/products', "Admin\AdminProductsController", array('as' => 'admin'));

    Route::resource('admin/roles', "Admin\AdminRolesController", array('as' => 'admin'));

    Route::resource('admin/users', "Admin\AdminUsersController", array('as' => 'admin'));

//------ Admin Orders ------
    Route::resource('admin/orders', "Admin\AdminOrdersController", array('as' => 'admin'));
    Route::post("admin/orders/updateindex", "Admin\AdminOrdersController@updateAjax")->name('admin.orders.updateindex');

    Route::resource('admin/comments', "Admin\AdminCommentsController", array('as' => 'admin'));
    Route::post("admin/comments/update", "Admin\AdminCommentsController@updateAjax")->name('admin.comments.update');

    Route::resource('admin/media', "Admin\AdminMediaController", array('as' => 'admin'));

    Route::get('admin/products/{id}/provider', ['uses' => 'Admin\AdminProductsController@getProviderById']);
    Route::get('admin/media/{id}/product', ['uses' => 'Admin\AdminMediaController@getProductById']);
});


Route::resource("/home", "UI\UIHomeController");

Route::get("/product/{id}", "UI\UIProductDetailController@index")->name('product.index');
Route::post("/product/{id}/comment", "UI\UIProductDetailController@addComment")->name('product.addcomment');
Route::get('/product/{id}/delete', 'UI\UIProductDetailController@deleteComment')->name('product.deletecomment');

Route::get("/home/category/{id}", "UI\UIHomeController@getProByCate")->name('home.getProByCate');
Route::get("/home/searchbyprice/{data}", "UI\UIHomeController@getProByPrice")->name('home.getProByPrice');

//--- UI ----
Route::post("user/login", "UI\UIUserController@login")->name('user.login');
//Route::post("user/logout", "UI\UIUserController@login")->name('user.logout');

Route::get('user/register', 'UI\UIUserController@registerShow')->name('user.register');
Route::post('user/register', 'UI\UIUserController@Register')->name('user.register.submit');
Route::get('user/verifyemail/{confirm_code}', 'UI\UIUserController@verifyEmail')->name('user.verifyemail');

// ----------- ACCOUNT ----------------
Route::group(['middleware' => ['logged']], function() {
    Route::get('user/account/{id}', 'UI\UIAccountController@show')->name('user.account');
    Route::get('user/order/{id}', 'UI\UIAccountController@orderDetail')->name('user.orderdetail');
    Route::get('user/profile/{id}', 'UI\UIAccountController@profile')->name('user.profile');
    Route::post('user/profile/{id}', 'UI\UIAccountController@profileUpdate')->name('user.profile.update');
    Route::post('user/order/canceled', 'UI\UIAccountController@orderCanceled')->name('user.ordercanceled');
    Route::put('user/profile/changepass', 'UI\UIAccountController@changePass')->name('user.changepass');
    Route::get('user/profile/requestmail/{id}', 'UI\UIAccountController@sendMail')->name('user.sendmail');
});

//------ Cart ------
Route::post("cart/addcart", "UI\UICartController@addCart")->name('cart.addcart');
Route::post("cart/plus", "UI\UICartController@plusCart")->name('cart.plus');
Route::post("cart/minus", "UI\UICartController@minusCart")->name('cart.minus');
Route::post("cart/remove", "UI\UICartController@removeItem")->name('cart.remove');
Route::get("cart", "UI\UICartController@show")->name("cart");
Route::get("checkout", "UI\UICartController@checkout")->name("checkout");
Route::post("checkout", "UI\UICartController@checkoutSubmit")->name("checkout");
Route::get("shipping", "UI\UICartController@shipping")->name("shipping");
Route::post("shippingAgree", "UI\UICartController@shippingSubmit")->name("shippingAgree");



//Route::get("/search","UI\UIHomeController@search")->name('home.search');
Route::get("/search", "UI\UIHomeController@search")->name('home.search');
Route::get("/home/searchbyprice/{data}", "UI\UIHomeController@getProByPrice")->name('home.getProByPrice');


//Make auth for routes
Auth::routes();

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'name', 'parent_id', 'is_active', 'created_at', 'updated_at'
    ];
    
    public function parent() {
        return $this->belongsTo('App\Category', 'parent_id', 'id');
    }
    
    public function children() {
        return $this->hasMany('App\Category' , 'parent_id', 'id');
    }
}

resources/views/admin/categories/create.blade.php
@extends ('layouts.admin')

@section('content')

<!-- general form elements -->
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Tạo danh mục sản phẩm</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <div class="row">
        <div class="col-md-8">
            <form role="form" action="{{ route('admin.categories.store') }}" method="POST" enctype='multipart/form-data'>
                <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
                <div class="box-body">
                    <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                        <label for="name">Tên Danh mục</label>
                        <input type="text" id="name" name="name" class="form-control" placeholder="Nhập tên danh mục">
                        <span class="text-danger">{!! $errors->first('name') !!}</span>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Danh mục này thuôc về</label>
                        <select id="parent_id" name="parent_id" class="form-control">
                            <option value="0" selected="true">-- Danh mục gốc --</option>
                            @foreach ($categories AS $category)
                            <option value="{{ $category->id }}">
                                {{ $category->name }}
                            </option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Lưu</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.box -->

@endsection

resources/views/admin/categories/edit.blade.php
@extends ('layouts.admin')

@section('content')

<!-- general form elements -->
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Tạo danh mục sản phẩm</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <div class="row">
        <div class="col-md-8">
            <form role="form" action="{{ route('admin.categories.update', $category->id) }}" method="POST" enctype='multipart/form-data'>
                <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
                <input type="hidden" name="_method" value="PUT">
                <div class="box-body">
                    <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                        <label for="name">Tên Danh mục</label>
                        <input type="text" id="name" name="name" class="form-control" value="{{ $category->name ? $category->name: old('name') }}">
                        <span class="text-danger">{!! $errors->first('name') !!}</span>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Danh mục này thuôc về</label>
                        <select id="parent_id" name="parent_id" class="form-control">
                            <option value="0">-- Danh mục gốc --</option>
                            @foreach ($categories AS $cate)
                            <option value="{{ $cate->id }}" {{ $cate->id == $category->parent_id ? 'selected' : '' }} >
                                {{ $cate->name }}
                            </option>
                            @endforeach
                        </select>
                    </div> 
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Lưu</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.box -->

@endsection

resources/views/admin/categories/index.blade.php
@extends ('layouts.admin')

@section('content')

@if (Session::has('notification'))
<div class="alert alert-success" id="notify">
    <button data-dismiss="alert" class="close">×</button>
    {!! Session::get('notification') !!}
</div>
@endif

<div class="row">
    <div class="col-sm-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Data Table With Full Features</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Tên</th>
                            <th>Chứa trong</th>
                            <th>Ngày tạo</th>
                            <th>Cập nhật vào</th>
                            <th>Hành động</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($categories AS $category)
                        <tr>
                            <td>{{ $category->id }}</td>
                            <td id="name_{{$category->id}}">{{ $category->name }}</td>
                            <td>
                                {{ $category->parent_id!=0 ? $category->parent->name:'Thư mục gốc' }}
                            </td>
                            <td>{{ $category->created_at }}</td>
                            <td>{{ $category->updated_at }}</td>
                            <td>
                                <div style="display: block; width: max-content">
                                    <a class="button-a edit-button" href="{{ route('admin.categories.edit', $category->id) }}" 
                                       title="Chỉnh sửa"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>&nbsp;
                                    <!--                                <a class="button-a delete-button" href="javascript:deleteA('category_{{$category->id}}')" 
                                                                       title="Xóa"><i class="fa fa-trash-o" aria-hidden="true"></i></a>&nbsp;-->
                                    <a class="button-a delete-button delete-fnt" data-type="1" data-id="{{$category->id }}"
                                       title="Xóa"><i class="fa fa-trash-o" aria-hidden="true"></i></a>&nbsp;
                                    <form id="fnt_{{$category->id}}" action="{{ route('admin.categories.destroy', $category->id) }}" method="POST">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
                                        <input type="hidden" name="_method" value="DELETE">
                                    </form>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                <div style="text-align: center">
                    {{ $categories->render() }}
                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>

@endsection